config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  resources :message, only:[:new, :create]
   get '/message/clear' => 'message#clear'
  resources :bulletins
  devise_for :users
  resources :posts
  root 'home#index'
  #  get '/' => 'posts#index'
  post 'tags/:tag' => 'posts#index', as: :tag
  get 'tags/:tag' => 'bulletins#index'

  # mailer

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bulletin.rb
class Bulletin < ApplicationRecord
  acts_as_taggable
  has_many :posts, dependent: :destroy
end

app/models/message.rb
class Message
  include ActiveModel::Model
  attr_accessor :email, :title, :message
  validates :title, :email, :message, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  acts_as_taggable
  belongs_to :user
  belongs_to :bulletin, optional: true
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many  :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :exception


end

app/controllers/bulletins_controller.rb
class BulletinsController < ApplicationController
  before_action :set_bulletin, only: %i[show edit update destroy]

  # GET /bulletins
  # GET /bulletins.json
  def index
    @posts = if params[:tag]
               Post.tagged_with(params[:tag]).page(params[:page]).order(created_at: :DESC)
             else
               Post.page(params[:page]).order(created_at: :DESC)
             end
  end

  # GET /bulletins/1
  # GET /bulletins/1.json
  def show; end

  # GET /bulletins/new
  def new
    @bulletin = Bulletin.new
  end

  # GET /bulletins/1/edit
  def edit; end

  # POST /bulletins
  # POST /bulletins.json
  def create
    @bulletin = Bulletin.new(bulletin_params)

    respond_to do |format|
      if @bulletin.save
        format.html { redirect_to @bulletin, notice: 'Bulletin was successfully created.' }
        format.json { render :show, status: :created, location: @bulletin }
      else
        format.html { render :new }
        format.json { render json: @bulletin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bulletins/1
  # PATCH/PUT /bulletins/1.json
  def update
    respond_to do |format|
      if @bulletin.update(bulletin_params)
        format.html { redirect_to @bulletin, notice: 'Bulletin was successfully updated.' }
        format.json { render :show, status: :ok, location: @bulletin }
      else
        format.html { render :edit }
        format.json { render json: @bulletin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bulletins/1
  # DELETE /bulletins/1.json
  def destroy
    @bulletin.destroy
    redirect_to bulletins
    respond_to do |format|
      format.html { redirect_to bulletins_url, notice: 'Bulletin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_bulletin
    @bulletin = Bulletin.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def bulletin_params
    params.require(:bulletin).permit(:title, :area)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @photo_background = Post.all.sample
    render layout: '_homeLayout'
  end
end

app/controllers/message_controller.rb
class MessageController < ApplicationController

def new
  @message = Message.new
end

def create
  @message = Message.new message_params

  if @message.valid?
    MessageMailer.contact(@message).deliver_now
    redirect_to message_clear_path
    flash[:notice] = "We have received your message and will be in touch soon!"
   else
     flash[:notice] = "There was an error sending your message. Please try again."
     render :new
  end
end

def clear
end


private

def message_params
  params.require(:message).permit(:title, :email, :message)
end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[show edit update destroy]

  # GET /posts
  # GET /posts.json

  def _sideBar
    @posts = Post.all.sample
  end

  def index
    @post = Post.all.sample
    @posts = if params[:tag]
               Post.tagged_with(params[:tag]).order("RANDOM()")
             else
               Post.all.order("RANDOM()")
             end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show; end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit; end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def post_params
    params.require(:post).permit(:title, :area, :image, :user_id, tag_list: [])
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bulletins_helper.rb
module BulletinsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/message_helper.rb
module MessageHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/bulletins/_form.html.erb
<%= form_with(model: bulletin, local: true) do |form| %>
  <% if bulletin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bulletin.errors.count, "error") %> prohibited this bulletin from being saved:</h2>

      <ul>
      <% bulletin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :bulletin_title %>
  </div>

  <div class="field">
    <%= form.label :area %>
    <%= form.text_field :area, id: :bulletin_area %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/bulletins/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <div class="well">
<h1 style="text-align: center;">Posts</h1>
<div class="table-reponsive">
<table class="table table-fit">
  <thead>
    <tr>
      <th>Title</th>
      <th>Area</th>
      <th>Tag List</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.area %></td>
        <td><%=post.tag_list%></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
  <div style="text-align: center;">
  <%= paginate @posts %>
  </div>
</div>

<br>
  <div style="float:left; width: 50%;">
    <%= link_to 'New post', new_post_path %>
  </div>
  <div style="text-align: right; float: left; width: 50%;">
    <%= link_to 'All', bulletins_path %> |
    <%= link_to 'Snap', tag_path('Snap') %> |
    <%= link_to 'Portrait', tag_path('Portrait') %>  |
    <%= link_to 'Landscape', tag_path('Landscape') %>  |
    <%= link_to 'Travel', tag_path('Travel') %> |
    <%= link_to 'B&W', tag_path('BlackandWhite') %> |
    <%= link_to 'Film', tag_path('Film') %>
  </div>


  </div>
</div>

app/views/home/index.html.erb
<style>
  h1 {
    background-color: rgba(255, 255, 255, 0.3);
    padding: 0.3rem;
    color: rgb(0,0,0);
    font-family: 'Source Sans Pro', sans-serif;
    font-weight: bold;

  }
  body{
    <% if @photo_background != nil  %>
    background-image: url("<%= @photo_background.image %>");
    <% else %>
    background-image: none;
    <%end%>
    background-size: cover;
    min-height: 100vh;
    margin: 0;
    display: flex;
    justify-content: center;
    align-items: center;
    height: 100%;
  }

 a{
   color: black;
  &:hover {

  }
 }
</style>



<div>
  <div class="container">
    <div class="col-md-12">
      <h1><%= link_to 'Welcome my Exhibition', posts_path, style: "font-size: 50px;"%></h1>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<!-- Navigation bar -->
<nav class="navbar navbar-fixed-top navbar-inverse">
	<div>
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
			</button>
			<%#= link_to 'Exhibition', root_path, class: 'navbar-brand', id: 'logo' %>
		</div>

		<div id="navbar" class="navbar-collapse collapse" style="padding-left: 30px; font-size: 8px;">
			<ul class="nav navbar-nav navbar-left">
				<li style="font-size: 8px;"><%= link_to 'Snap', tag_path('Snap'), method: :post %> </li>
				<li style="font-size: 8px;"><%= link_to 'Portrait', tag_path('Portrait'), method: :post  %></li>
				<li style="font-size: 8px;"><%= link_to 'Landscape', tag_path('Landscape'), method: :post  %></li>
				<li style="font-size: 8px;"><%= link_to 'Travel', tag_path('Travel'), method: :post  %></li>
				<li style="font-size: 8px;"><%= link_to 'B&W', tag_path('BlackandWhite'), method: :post  %></li>
				<li style="font-size: 8px;"><%= link_to 'Film', tag_path('Film'), method: :post  %></li>
			</ul>
			<ul class="nav navbar-nav navbar-right" style="  margin-right: 20px;">
				<% if user_signed_in? %>
					<% if current_user.id == 1%>
					<!-- 관리자만 새글쓰게끔. -->
						<li style="font-size: 8px;"><%= link_to 'Main', posts_path %></li>
						<li style="font-size: 8px;"><%= link_to 'New Post', new_post_path %></li>
						<li style="font-size: 8px;"><%= link_to 'Posts List', bulletins_path %></li>
						<li style="font-size: 8px;"><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
					<% else %>
						<li style="font-size: 8px;"><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
					<% end %>
				<% else %>
					<li style="font-size: 8px;"><%= link_to 'Main', posts_path %></li> |
					<li style="font-size: 8px;"><%= link_to 'Contact', new_message_path %></li>
					<!-- <li><%= link_to('Sign in', new_user_session_path) %></li> -->
				<% end %>
			</ul>
		</div><!--/.nav-collapse -->
	</div><!--/.container-fluid -->
</nav>

app/views/layouts/_homeLayout.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Exhibition</title>
    <%= csrf_meta_tags %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Exhibition" />
    <meta name="keywords" content="Korean amateur Photographer" />
    <meta name="author" content="Dahun Yoo" />

      <!-- Facebook and Twitter integration -->
    <meta property="og:title" content=""/>
    <meta property="og:image" content=""/>
    <meta property="og:url" content=""/>
    <meta property="og:site_name" content=""/>
    <meta property="og:description" content=""/>
    <meta name="twitter:title" content="" />
    <meta name="twitter:image" content="" />
    <meta name="twitter:url" content="" />
    <meta name="twitter:card" content="" />

    <!-- Place favicon.ico and apple-touch-icon.png in the root directory -->
    <link rel="shortcut icon" href="favicon.ico">
    <link href='https://fonts.googleapis.com/css?family=Varela+Round' rel='stylesheet' type='text/css'>
     <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:200" rel="stylesheet">
     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">


    <!-- <link href="https://fonts.googleapis.com/css?family=Bungee+Shade" rel="stylesheet"> -->

    <!-- Animate.css -->
    <!-- <link rel="stylesheet" href="css/animate.css"> -->
    <!-- Icomoon Icon Fonts-->
    <!-- <link rel="stylesheet" href="css/icomoon.css"> -->
    <!-- Bootstrap  -->
    <!-- <link rel="stylesheet" href="css/bootstrap.css"> -->
    <!-- Theme style  -->
    <!-- <link rel="stylesheet" href="css/style.css"> -->
    <!-- Magnific Popup -->
    <!-- <link rel="stylesheet" href="css/magnific-popup.css"> -->


    <!-- Modernizr JS -->
    <!-- <script src="js/modernizr-2.6.2.min.js"></script> -->
    <!-- FOR IE9 below -->
    <!--[if lt IE 9]>
    <script src="js/respond.min.js"></script>
    <![endif]-->

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body id="fade">


<!-- About -->

    <!--End of fh5co-aside  -->
    <!-- End of About -->

    <%= yield %>


    <!-- End of fh5co -->


  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">``
    <title>Exhibition</title>
    <%= csrf_meta_tags %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Exhibition" />
    <meta name="keywords" content="Korean amateur Photographer" />
    <meta name="author" content="Dahun Yoo" />

      <!-- Facebook and Twitter integration -->
    <meta property="og:title" content=""/>
    <meta property="og:image" content=""/>
    <meta property="og:url" content=""/>
    <meta property="og:site_name" content=""/>
    <meta property="og:description" content=""/>
    <meta name="twitter:title" content="" />
    <meta name="twitter:image" content="" />
    <meta name="twitter:url" content="" />
    <meta name="twitter:card" content="" />

    <!-- Place favicon.ico and apple-touch-icon.png in the root directory -->
    <link rel="shortcut icon" href="favicon.ico">
    <link href='https://fonts.googleapis.com/css?family=Varela+Round' rel='stylesheet' type='text/css'>
    <!-- <link href="https://fonts.googleapis.com/css?family=Bungee+Shade" rel="stylesheet"> -->

    <!-- Animate.css -->
    <!-- <link rel="stylesheet" href="css/animate.css"> -->
    <!-- Icomoon Icon Fonts-->
    <!-- <link rel="stylesheet" href="css/icomoon.css"> -->
    <!-- Bootstrap  -->
    <!-- <link rel="stylesheet" href="css/bootstrap.css"> -->
    <!-- Theme style  -->
    <!-- <link rel="stylesheet" href="css/style.css"> -->
    <!-- Magnific Popup -->
    <!-- <link rel="stylesheet" href="css/magnific-popup.css"> -->


    <!-- Modernizr JS -->
    <!-- <script src="js/modernizr-2.6.2.min.js"></script> -->
    <!-- FOR IE9 below -->
    <!--[if lt IE 9]>
    <script src="js/respond.min.js"></script>
    <![endif]-->

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <div id="fh5co-page">
      <!-- <%= render 'layouts/header'%> -->
<!-- About -->

    <!--End of fh5co-aside  -->
    <!-- End of About -->

    <%= yield %>

    </div>
    <!-- End of fh5co -->
  </body>
</html>

app/views/message/clear.html.erb
<div class="container" style="padding-top: 50px;">
  <div class="well">

    <h1>Thank you for your Message!</h1>
  </div>


</div>

app/views/message/new.html.erb
<div class="container" style="margin-top: 40px;">
  <div class="well">
    <h1 style="margin-top: 20px;"> Contact me !</h1>
    <div style="text-align: center;">
    <p>If any question, please contact me. I'll reply as soon as possible</p>
    <p>궁금하신 점이 있으시다면 연락주세요! 촬영기기부터 촬영장소,
      등 언제든지 환영입니다. <br> 촬영문의도 받고 있습니다. 모델도 항상 구하고 있으니 부담없이
    연락주세요.</p>
    </div>
    <hr>
    <%= form_for @message, url:message_index_path do |m|%>
  <div style="padding: 0px 30px 30px 30px;">
  
    <div class="field">
      <%= m.label :email%>
      <%= m.text_field :email, required: true, style: "width: 100%;"%>
    </div>
    <div class="field">
      <%= m.label :title%>
      <%= m.text_field :title, required: true,style: "width: 100%;"%>
    </div>
    <div class="field">
      <%= m.label :message%>
      <%= m.text_area :message, required: true, style: "width: 100%; height: 200px;"%>
    </div>
    <div class="action", style="text-align: right;">
      <%= m.submit 'Send messsages', class: "button"%>
    </div>
    <%end%>
    </div>
  </div>

</div>

app/views/posts/_form.html.erb
<div class="well" style="padding: 10px; margin-top: 150px;">
<h1>New Post</h1>
<%= form_with(model: post, html: {multipart: true}, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :post_title %>
  </div>

  <div class="field">
    <%= form.label :area %>
    <%= form.text_field :area, id: :post_area %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image, id: :post_image %>
  </div>
    <%= form.hidden_field :user_id, id: :post_user_id, value: current_user.id %>
<div class="field">

</div>
<hr>
  <div class="actions">
    <%= form.label :tag_list%>
    <%= form.check_box :tag_list, {multiple: true}, 'Snap'%> Snap <br>
    <%= form.check_box :tag_list, {multiple: true}, 'Portrait'%> Portrait <br>
    <%= form.check_box :tag_list, {multiple: true}, 'Landscape'%> Landscape <br>
    <%= form.check_box :tag_list, {multiple: true}, 'Travel'%> Travel <br>
    <%= form.check_box :tag_list, {multiple: true}, 'BlackandWhite'%> B/W <br>
    <%= form.check_box :tag_list, {multiple: true}, 'Film'%> Film <br>
    <hr>
    <%= form.submit %>
  </div>
<% end %>
</div>

app/views/posts/_indexTagged.html.erb
<% @posts.each do |post| %>
    <div class="grid-item item animate-box" data-animate-effect="fadeIn">
        <a href="<%= image_path post.image%>" class="image-popup" title="<%= post.title%>" >

        <div class="img-wrap">
          <img src="<%= image_path post.image%>" alt="" class="img-responsive">
        </div>

        <div class="text-wrap">
          <div class="text-inner popup">
            <div>
              <h2><%= post.title%></h2>
              <span><%= post.area%></span>
            </div>
          </div>
        </div>

      </a>
    </div>
<%end%>

app/views/posts/_sideBar.html.erb
<div class="aside-toggle btn-circle">
  <a href=""><span></span><em>About Me</em></a>
</div>


<div id="fh5co-aside">

  <% if @post != nil%>
  <div class="image-bg" style="background: url(<%= @post.image%>)"></div>
  <% else %>
  <div class="image-bg"></div>
  <%end%>
  <div class="overlay"></div>
  <div class="row">
    <div class="col-md-12">
      <div id="fh5co-aside-inner">
        <div class="row" id="fh5co-bio">
          <div class="col-md-12" style="margin-top: 20px;">
            <h2>Yoo Dahun <small>유다훈</small></h2>
          </div>
          <div class="col-md-9">
            <ul>
              <li>Live in Fukuoka, Japan</li>
              <hr>
              <li>X-Pro1</li>
                <ul>
                  <li> XF 18mm f2 </li>
                  <li> XF 56mm f1.2 </li>
                </ul>
              <hr>
                <li> Korea, Japan </li>
                <li> Snap, Landscape, Portrait </li>
            </ul>
          </div>
          <div class="col-md-3">

          </div>

          <div class="col-md-12 fh5co-social" style="text-align: center;">
            <hr>
            <a href="https://www.instagram.com/dahunyoo/" target="_blank"><i class="icon-instagram"> Instagram   </i></a>     |
            <a href="http://tty4032.blog.me" target="_blank"><i class="icon-external-link-square">    NaverBlog</i></a>
          </div>
          <div class="col-md-12" style="margin-top: 20px;">
            <p>Thanks to LikeLion</p>
            <div>&copy; Photo by Dahun, All Rights Reserved</p></div>
            <div>&copy; 2016 Free HTML5 Template. All Rights Reserved. Designed by <a href="http://gettemplates.co/">GetTemplates</a></div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<%= render 'sideBar' %>

	<div class="container-fluid" id="fh5co-image-grid">
		<div class="grid">
		  <div class="grid-sizer">


	 		<%= render 'indexTagged'%>

			</div>
		</div>
		<!-- End of grid -->
	</div>
	<!-- End of Container Fluid -->

app/views/posts/new.html.erb
<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.area %>
</p>

<p>
  <strong>Image:</strong>
  <%= @post.image %>
</p>

<p>
  <strong>User:</strong>
  <%= @post.user %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>